server:
  port: 8090

logging:
  file:
    name: logs/notification-service.log
  level:
    root: INFO
    org.springframework.kafka: INFO
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: parthlakhani112001@gmail.com
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.debug: true
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"