spring:
  datasource:
#    url: jdbc:postgresql://localhost:5434/orderdb
#    username: postgres
#    password: postgres
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/orderdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      properties:
        max.block.ms: 3000
        request.timeout.ms: 3000
      retries: 1

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8082

services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8085}
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8087}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

