server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/productdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true