server:
  port: 8087

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5435/productdb
#    username: postgres
#    password: postgres
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/productdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always