server:
  port: 8091

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5438/reviewdb?options=-c%20TimeZone=Asia/Kolkata
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true